project_name: cv_training
run_name: resnet18_baseline

dataset:
  name: CustomDataset
  path: ./data/inaturalist_12K/
  img_size: [256,256]
  class_names: ['Plantae', 'Mammalia', 'Animalia', 'Reptilia', 'Amphibia', 'Aves', 'Fungi', 'Arachnida', 'Mollusca', 'Insecta']
  batch_size: 500

train:
  epochs: 2
  lr: 0.001
  optimizer: adam
  scheduler: step
  step_size: 10
  gamma: 0.1
  weight_decay: 0.0001

model:
  name: simplecnn
  num_layers: 5
  filters: [32, 64, 128, 256, 512]
  kernel_size: 3
  activation: relu
  dense_neurons: 512
  num_classes: 10
  in_channels: 3

logging:
  log_interval: 10